# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clientes.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63lientes.proto\x12\x08\x63lientes\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8f\x04\n\x07\x43liente\x12\x0f\n\x02id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x1b\n\x0e\x66\x65\x63ha_creacion\x18\x02 \x01(\tH\x01\x88\x01\x01\x12 \n\x13\x66\x65\x63ha_actualizacion\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x14\n\x07nombres\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x16\n\tapellidos\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\x1b\n\x0eidentificacion\x18\x06 \x01(\tH\x05\x88\x01\x01\x12\x1d\n\x10\x66\x65\x63ha_nacimiento\x18\x07 \x01(\tH\x06\x88\x01\x01\x12\x13\n\x06genero\x18\x08 \x01(\tH\x07\x88\x01\x01\x12\x16\n\tdireccion\x18\t \x01(\tH\x08\x88\x01\x01\x12\x15\n\x08telefono\x18\n \x01(\tH\t\x88\x01\x01\x12\x13\n\x06\x63orreo\x18\x0b \x01(\tH\n\x88\x01\x01\x12\x18\n\x0btipoCliente\x18\x0c \x01(\tH\x0b\x88\x01\x01\x12\x15\n\x08sitioWeb\x18\r \x01(\tH\x0c\x88\x01\x01\x42\x05\n\x03_idB\x11\n\x0f_fecha_creacionB\x16\n\x14_fecha_actualizacionB\n\n\x08_nombresB\x0c\n\n_apellidosB\x11\n\x0f_identificacionB\x13\n\x11_fecha_nacimientoB\t\n\x07_generoB\x0c\n\n_direccionB\x0b\n\t_telefonoB\t\n\x07_correoB\x0e\n\x0c_tipoClienteB\x0b\n\t_sitioWeb\"\x1a\n\x0cQueryCliente\x12\n\n\x02id\x18\x01 \x01(\t\"X\n\x10RespuestaCliente\x12\x0f\n\x07mensaje\x18\x01 \x01(\t\x12\'\n\x07\x63liente\x18\x02 \x01(\x0b\x32\x11.clientes.ClienteH\x00\x88\x01\x01\x42\n\n\x08_cliente2\x95\x01\n\x08\x43lientes\x12?\n\x0c\x43rearCliente\x12\x11.clientes.Cliente\x1a\x1a.clientes.RespuestaCliente\"\x00\x12H\n\x10\x43onsultarCliente\x12\x16.clientes.QueryCliente\x1a\x1a.clientes.RespuestaCliente\"\x00\x42\x31\n\x18\x63o.edu.uniandes.misw4406B\rClientesProtoP\x01\xa2\x02\x03\x43LIb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clientes_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030co.edu.uniandes.misw4406B\rClientesProtoP\001\242\002\003CLI'
  _CLIENTE._serialized_start=62
  _CLIENTE._serialized_end=589
  _QUERYCLIENTE._serialized_start=591
  _QUERYCLIENTE._serialized_end=617
  _RESPUESTACLIENTE._serialized_start=619
  _RESPUESTACLIENTE._serialized_end=707
  _CLIENTES._serialized_start=710
  _CLIENTES._serialized_end=859
# @@protoc_insertion_point(module_scope)
